OUTPUT_FILE = r'c:/99_temp/202112091521/'
OUTPUT_SHOP_FILENAME = r'shop.csv'
OUTPUT_BUS_STOP_FILENAME = r'bus_stop.csv'
BUS_STOP_GJSON = r'bus_stop.geojson'
CYCLEWAY_GJSON = r'cycleway.geojson'
BICYCLE_GJSON = r'bicycle.geojson'